language: java
jdk: openjdk8
install: true
jobs:
  include:
    - stage: starter
      name: "Jupiter Starter Sample: Maven & Scala"
      script: cd $TRAVIS_BUILD_DIR && ./mvnw test
    - stage: starter
      name: "Jupiter Starter Sample: Maven & Scala build JDK11"
      script: cd $TRAVIS_BUILD_DIR && ./mvnw test
      jdk: openjdk11
    - stage: starter
      name: "Jupiter Starter Sample: Maven & Scala build for Java 11"
      script: cd $TRAVIS_BUILD_DIR && ./mvnw test -f pom-java11.xml
      jdk: openjdk11
cache:
  directories:
    - ~/.m2
